solids:
  read_file:
    inputs:
      file_path:
        "/Users/alexandre.miyazaki/Documents/git-personal/try-dagster/README.md"
  count_file_lines_and_show:
    config:
      phrase_param: "asdfg"
